### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by tinaYA524** [maxi-w/CLIP-SAM#2]
```
Traceback (most recent call last):
  File "/home/tina/Desktop/CLIP-SAM-main/main.py", line 48, in <module>
    def retriev(elements: list[Image.Image], search_text: str) -> int:
TypeError: 'type' object is not subscriptable
```

Following your tutorial, I went to the step of directly running `main.ipynb`, but the above error occurred. Please advise me on how to solve this bug. Thank you very much!

**Comment by tinaYA524** [comment]
The issue has been resolved:
Change the function definition to the following format:
`def retriev(elements: list, search_text: str) -> int:`

**Comment by ccmCCMfk** [comment]
> The issue has been resolved: Change the function definition to the following format: `def retriev(elements: list, search_text: str) -> int:`

I have a question that  if the prompt Hello, I have a question to ask, can this prompt be changed to a sentence or a phrase?
